name: ChestDump
main: net.jmhertlein.chestdump.ChestDumpPlugin
version: ${version}-${buildNumber}
softdepend: [WorldEdit]
commands:
    cdump:
        description: Dumps contents of all chests in WE selection
        usage: /cdump [id]
        aliases: [cd]