name: ChestSearch
main: net.jmhertlein.chestsearch.ChestSearchPlugin
version: ${version}-${buildNumber}
softdepend: [WorldEdit]
commands:
    csearch:
        description: Finds all chests in WE selection
        usage: /csearch [start|stop|inspect|tp]
        aliases: [cs]